name: Dependencies
on:
  schedule:
    - cron: "0 0 * * 0"  # Run weekly on Sundays
  workflow_dispatch:

jobs:
  dependencies:
    name: Check for dependency updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for npm updates
        uses: MeilCli/npm-update-check-action@v5
        id: check
      
      - name: Create Issue if updates available
        if: steps.check.outputs.has_npm_update == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const updates = JSON.parse(process.env.NPM_UPDATE_PACKAGES)
            const body = `## Dependency Updates Available\n\n${
              updates.map(pkg => (
                `- **${pkg.packageName}**: ${pkg.currentVersion} -> ${pkg.newVersion}`
              )).join('\n')
            }\n\nPlease review these updates and create a pull request if appropriate.`
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '📦 Dependency updates available',
              body: body,
              labels: ['dependencies']
            })
        env:
          NPM_UPDATE_PACKAGES: ${{ steps.check.outputs.npm_update_packages }} 